// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpikMIo3n9FauKJsZvdSq-5bIkzCQcrck',
    appId: '1:177753038878:web:053a5a1e31e343505a4e0f',
    messagingSenderId: '177753038878',
    projectId: 'trashtotreasure-7f7f1',
    authDomain: 'trashtotreasure-7f7f1.firebaseapp.com',
    storageBucket: 'trashtotreasure-7f7f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCup3d8dsNxxVr_8XnnUe6aJrLqMban4E',
    appId: '1:177753038878:android:2aeea56ce2ce56ab5a4e0f',
    messagingSenderId: '177753038878',
    projectId: 'trashtotreasure-7f7f1',
    storageBucket: 'trashtotreasure-7f7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqW33PcUm3WI7Y_OVkNw1qSHKLp-9JL-g',
    appId: '1:177753038878:ios:75028ea16d5457445a4e0f',
    messagingSenderId: '177753038878',
    projectId: 'trashtotreasure-7f7f1',
    storageBucket: 'trashtotreasure-7f7f1.firebasestorage.app',
    androidClientId: '177753038878-l339kj9i73nctg04jpt7srcgt2d4atqs.apps.googleusercontent.com',
    iosClientId: '177753038878-1ug9g3n4qnm1d030knhge4bud5k9hfl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashToTreasure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqW33PcUm3WI7Y_OVkNw1qSHKLp-9JL-g',
    appId: '1:177753038878:ios:75028ea16d5457445a4e0f',
    messagingSenderId: '177753038878',
    projectId: 'trashtotreasure-7f7f1',
    storageBucket: 'trashtotreasure-7f7f1.firebasestorage.app',
    androidClientId: '177753038878-l339kj9i73nctg04jpt7srcgt2d4atqs.apps.googleusercontent.com',
    iosClientId: '177753038878-1ug9g3n4qnm1d030knhge4bud5k9hfl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashToTreasure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpikMIo3n9FauKJsZvdSq-5bIkzCQcrck',
    appId: '1:177753038878:web:5dd4f5ba33f6b1685a4e0f',
    messagingSenderId: '177753038878',
    projectId: 'trashtotreasure-7f7f1',
    authDomain: 'trashtotreasure-7f7f1.firebaseapp.com',
    storageBucket: 'trashtotreasure-7f7f1.firebasestorage.app',
  );

}